---
kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build binary
    image: alpine
    commands:
      - ./build.sh
      - cp /usr/local/bin/qbittorrent-nox $(pwd)/build/qbittorrent-nox-$(echo $(/usr/local/bin/qbittorrent-nox --version) | cut -d' ' -f2)-static-${DRONE_STAGE_ARCH}
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: build/qbittorrent-nox*
      title: Release ${DRONE_TAG}
    when:
      event:
        - tag

---
kind: pipeline
type: docker
name: arm

platform:
  os: linux
  arch: arm

steps:
  - name: build binary
    image: alpine
    commands:
      - echo "building in $(pwd)"
      - apk add --no-cache bash wget curl
      - wget -qO $(pwd)/qbittorrent-nox-static-musl.sh https://git.io/JvLcZ
      - chmod 700 $(pwd)/qbittorrent-nox-static-musl.sh
      - $(pwd)/qbittorrent-nox-static-musl.sh
      - $(pwd)/qbittorrent-nox-static-musl.sh all -b "$(pwd)/qbittorrent-build"
      - $(pwd)/qbittorrent-nox-static-musl.sh install -b "$(pwd)/qbittorrent-build"
      - cp /usr/local/bin/qbittorrent-nox $(pwd)/build/qbittorrent-nox-$(echo $(/usr/local/bin/qbittorrent-nox --version) | cut -d' ' -f2)-static-${DRONE_STAGE_ARCH}
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: build/qbittorrent-nox*
      title: Release ${DRONE_TAG}
    when:
      event: tag

---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build binary
    image: alpine
    commands:
      - echo "building in $(pwd)"
      - apk add --no-cache bash wget curl
      - wget -qO $(pwd)/qbittorrent-nox-static-musl.sh https://git.io/JvLcZ
      - chmod 700 $(pwd)/qbittorrent-nox-static-musl.sh
      - $(pwd)/qbittorrent-nox-static-musl.sh
      - $(pwd)/qbittorrent-nox-static-musl.sh all -b "$(pwd)/qbittorrent-build"
      - $(pwd)/qbittorrent-nox-static-musl.sh install -b "$(pwd)/qbittorrent-build"
      - cp /usr/local/bin/qbittorrent-nox $(pwd)/build/qbittorrent-nox-$(echo $(/usr/local/bin/qbittorrent-nox --version) | cut -d' ' -f2)-static-${DRONE_STAGE_ARCH}
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: build/qbittorrent-nox*
      title: Release ${DRONE_TAG}
    when:
      event: tag
